# .github/workflows/docker.yml
name: Docker Build

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build binary for Docker
      run: |
        # Build statically linked binary for Alpine
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static"' -o migratrix .
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          migratrix/migratrix:latest
          migratrix/migratrix:${{ github.ref_name }}
        labels: |
          org.opencontainers.image.title=Migratrix
          org.opencontainers.image.description=Database migration and data transformation tool
          org.opencontainers.image.source=https://github.com/migratrix/migratrix
          org.opencontainers.image.version=${{ github.ref_name }}