# .github/workflows/docker.yml
name: Docker Build

on:
  push:
    tags:
      - 'agent-v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build .NET application for Docker
        run: |
          dotnet publish src/Migratrix/Migratrix.Api.Agent \
            --configuration Release \
            --runtime linux-x64 \
            --self-contained true \
            --output ./dist/linux-x64 \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=true
          
          # Rename executable
          mv ./dist/linux-x64/Migratrix.Api.Agent ./dist/linux-x64/migratrix-agent

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/code-fighter-labs/migratrix-agent:latest
            ghcr.io/code-fighter-labs/migratrix-agent:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.title=Migratrix Agent
            org.opencontainers.image.description=Database migration and data transformation agent
            org.opencontainers.image.source=https://github.com/code-fighter-labs/migratrix
            org.opencontainers.image.version=${{ github.ref_name }}